config/routes.rb
Last::Application.routes.draw do
  get "sessions/create"
  get "sessions/destroy"
  get "sessions/new"
  get "users/new"
  get "users/show"
  get "users/edit"
  resources :users
  resources :sessions, only: [:new,:create,:destroy]

  root 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def authorize
  	if current_user.nil?
  		session[:protected_page] = request.fullpath
  		redirect_to root_url, notice: 'You must login to view this page.'
  	end
  end

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def login(user)
  	reset_session
  	session[:user_id] = user.id
  end

  def logout
  	reset_session
  	session[:user_id] = nil
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		redirect_path = events_path
  		if session[:protected_page]
  			redirect_path = session[:protected_page]
  			session[:protected_page] = nil
  		end
  		login(user)
  		redirect_to redirect_path, notice: 'Logged In'
  	else
  		redirect_to root_path, alert: 'Invalid Email/Password'
  	end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Logged Out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params);
  	if @user.save
  		login(@user)
  		redirect_to root_path, notice: "Account created"
  	else
  		render :new, alert: "Error"
  	end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to root_path, notice: 'Account updated'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    logout
    redirect_to root_path, notice: 'Account Deleted'
  end

  private
  	def set_user
	  		@user = current_user
	  	end

		def user_params
			params.require(:user).permit(:name,:email,:password,:password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
	def title(page_title, show_title = true)
		content_for(:title) { page_title.to_s }
		@show_title = show_title
	end

	def show_title?
		@show_title
	end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% #if !current_user %>
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <%# else %>
        <%# link_to 'Home/Events', events_path, class: 'navbar-brand' %>
      <%# end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if current_user %>
    <%= link_to 'Profile', users_show_path, class: 'navbar-brand' %>
    <%= link_to 'Sign Out', sessions_destroy_path, class: 'navbar-brand' %>
    <% else %>
    <%= link_to 'Sign Up', users_new_path, class: 'navbar-brand' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Last</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
      <%= render 'layouts/navigation' %>
    </header>
	<main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>

</body>
</html>

app/views/users/_formuser.html.erb
<div class="jumbotron">
	<legend>Register</legend>
	<%= bootstrap_form_for(@user, style: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
		<%= f.alert_message "Oops got some errors" %>
		<%= f.text_field :name, label: "Username:", placeholder: 'Username' %>
		<%= f.text_field :email, label: "Email", placeholder: 'Email' %>
		<%= f.password_field :password, label: "Password", placeholder: 'Password' %>
		<%= f.password_field :password_confirmation, label: "Confirm Password", placeholder: 'Confirmation' %>
		<%= f.form_group do %>
			<%= f.submit 'Submit', class: 'btn btn-primary'%>
		<% end %>
	<% end %>
</div>

app/views/users/_user.html.erb
<%= div_for user do %>
	<h2> <%# link_to_unless_current user.name, event_path(user) %></h2>
	<p><strong>Username:</strong> <%= user.name %></p>
	<p><strong>Email:</strong> <%= user.email %></p>
	<p>
			<%= link_to 'Edit', edit_user_path(user) %> |
			<%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: 'Really are you sua?' } %>
	</p>
<% end %>

app/views/users/edit.html.erb
<% title 'Update Account' %>

<%= render 'formuser' %>
<!--<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>-->

app/views/users/new.html.erb
<% title 'Sing Up' %>

<%= render 'formuser' %>

<!--<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>-->

app/views/users/show.html.erb
<% title "Account: #{@user.name}" %>

<%= render @user %>
<!--<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>-->